don't do tests for logo.png, just try symlink and fail gracefully

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -26,8 +26,8 @@ if [ "$action" != configure ]
 fi
 
 fix_dir_perms(){
-	chgrp www-data -R /usr/share/grase/www/
-	chmod ag+rw -R /usr/share/grase/www/images/logo.png /usr/share/grase/www/radmin/templates_c /usr/share/grase/www/uam/templates_c
+	chgrp www-data -R /usr/share/grase/www/ || true
+	chmod ag+rw -R /usr/share/grase/www/images/logo.png /usr/share/grase/www/radmin/templates_c /usr/share/grase/www/uam/templates_c || true
 
 }
 
@@ -36,10 +36,12 @@ copy_favicon(){
 }
 
 link_logo(){
-    if [[ ! -a /usr/share/grase/www/images/logo.png ]]
-    then
-        ln -s graselogo.png /usr/share/grase/www/images/logo.png || true
-    fi
+    #if [[ ! -a /usr/share/grase/www/images/logo.png ]]
+    #then
+    
+    # Don't worry about tests, will fail silently
+    ln -s graselogo.png /usr/share/grase/www/images/logo.png > /dev/null || true
+    #fi
 
 }
 #DEBHELPER#
